#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

if [[ -f "${PROJECT_DIR}/.env" ]]; then
    set -a
    # shellcheck disable=SC1091
    source "${PROJECT_DIR}/.env"
    set +a
fi

PYTHON="${PYTHON:-python}"
PLANNER_MODEL_ID="${PLANNER_MODEL_ID:-${MODEL_ID:-${DEEPSEEK_MODEL_ID:-deepseek-v4-flash}}}"
# Use the previous SiliconFlow Qwen3-8B defaults.
ROUTER_MODEL_ID="${ROUTER_MODEL_ID:-${SILICONFLOW_MODEL_ID:-Qwen/Qwen3-8B}}"
WORKER_MODEL_ID="${WORKER_MODEL_ID:-${SILICONFLOW_MODEL_ID:-Qwen/Qwen3-8B}}"
DEEPSEEK_API_BASE="${DEEPSEEK_API_BASE:-https://api.deepseek.com}"
QWEN_API_BASE="${QWEN_API_BASE:-${SILICONFLOW_API_BASE:-https://api.siliconflow.cn/v1}}"
QWEN_API_KEY="${QWEN_API_KEY:-${SILICONFLOW_API_KEY:-}}"
API_BASE="${QWEN_API_BASE}"
LOCAL_BASE="${QWEN_API_BASE}"
API_KEY="${QWEN_API_KEY}"
export UNO_VERBOSE_RESPONSES="${UNO_VERBOSE_RESPONSES:-1}"
export SUBAGENT_VERBOSE="${SUBAGENT_VERBOSE:-1}"

if [[ -z "${QWEN_API_KEY}" ]]; then
    echo "QWEN_API_KEY or SILICONFLOW_API_KEY must be set before running this script." >&2
    exit 2
fi

for cert_var in SSL_CERT_FILE REQUESTS_CA_BUNDLE CURL_CA_BUNDLE; do
    cert_path="${!cert_var:-}"
    if [[ -n "${cert_path}" && ! -f "${cert_path}" ]]; then
        : "Unset ${cert_var}: file not found (${cert_path})"
        unset "${cert_var}"
    fi
done

EVAL_OUT="${EVAL_OUT:-${PROJECT_DIR}/data/eval}"
export TOOLBENCH_DATA_DIR="${TOOLBENCH_DATA_DIR:-${PROJECT_DIR}/data/toolbench/ToolACE}"
RUN_NAME="${RUN_NAME:-deepseek_v4_flash_qwen3_8b_router_toolbench}"
GEN_WORKERS="${GEN_WORKERS:-4}"
VERIFY_WORKERS="${VERIFY_WORKERS:-4}"
PASS_K="${TOOLBENCH_PASS_K:-1}"
MAX_TASKS="${MAX_TASKS:-1}"
DRY_RUN="${DRY_RUN:-0}"
EXTRA_ARGS=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run)
            DRY_RUN=1
            shift
            ;;
        --max-tasks)
            MAX_TASKS="$2"
            shift 2
            ;;
        --out-dir)
            OUT_DIR="$2"
            shift 2
            ;;
        --pass-k)
            PASS_K="$2"
            shift 2
            ;;
        --)
            shift
            EXTRA_ARGS+=("$@")
            break
            ;;
        *)
            EXTRA_ARGS+=("$1")
            shift
            ;;
    esac
done

TIMESTAMP="$(date +%Y%m%d_%H%M)"
OUT_DIR="${OUT_DIR:-${EVAL_OUT}/${RUN_NAME}_${TIMESTAMP}}"
mkdir -p "${OUT_DIR}"
LOG_FILE="${OUT_DIR}/run.log"
: > "${LOG_FILE}"
exec > >(tee -a "${LOG_FILE}") 2>&1

FIXED_UNO_POOLS_PATH="${OUT_DIR}/pools.qwen3_8b_fixed_worker.yaml"
cat > "${FIXED_UNO_POOLS_PATH}" <<EOF
policy_models:
  - ${PLANNER_MODEL_ID}
  - ${ROUTER_MODEL_ID}

models:
  - id: ${WORKER_MODEL_ID}
    usd_per_1m_input: 0.072
    usd_per_1m_output: 0.287
    api_base: ${QWEN_API_BASE}
    api_key: ${QWEN_API_KEY}
    description: >
      Qwen3-8B worker model. This run-local pool is generated by
      scripts/run_toolbench_qwen3_8b_fixed_routing.sh so ToolBench
      delegation is clamped to ${WORKER_MODEL_ID}.
    allowed_skills:
      - direct_answer
      - reason
      - read_code
      - execute_python
      - execute_shell

skills:
  - id: direct_answer
    description: "Answer the question directly without special tools."
  - id: reason
    description: "Multi-step logical reasoning or chain-of-thought analysis."
  - id: read_code
    description: "Read and understand source code."
  - id: execute_python
    description: "Write and execute Python code to compute a result."
  - id: execute_shell
    description: "Run shell commands for system-level tasks."

fallbacks: {}
pool_ablations: {}
EOF
export UNO_POOLS_PATH="${FIXED_UNO_POOLS_PATH}"

CMD=(
    "${PYTHON}" -m eval_pipeline
    --router planner
    --bench toolbench
    --api_key "${API_KEY}"
    --api_base "${API_BASE}"
    --local_base "${LOCAL_BASE}"
    --local_model "${PLANNER_MODEL_ID}"
    --router_model "${ROUTER_MODEL_ID}"
    --output_dir "${OUT_DIR}"
    --gen_workers "${GEN_WORKERS}"
    --verify_workers "${VERIFY_WORKERS}"
    --pass-k "${PASS_K}"
)

if [[ -n "${MAX_TASKS}" ]]; then
    CMD+=(--max_tasks "${MAX_TASKS}")
fi
CMD+=("${EXTRA_ARGS[@]}")

{
    echo "========================================"
    echo "ToolBench DeepSeek Planner + Qwen3-8B Fixed Routing Eval"
    echo "Project:       ${PROJECT_DIR}"
    echo "Planner model: ${PLANNER_MODEL_ID}"
    echo "Router model:  ${ROUTER_MODEL_ID}"
    echo "Worker model:  ${WORKER_MODEL_ID}"
    echo "API_BASE:      ${API_BASE}"
    echo "LOCAL_BASE:    ${LOCAL_BASE}"
    echo "QWEN_API_BASE: ${QWEN_API_BASE}"
    echo "Output:        ${OUT_DIR}"
    echo "toolbench_data:${TOOLBENCH_DATA_DIR}"
    echo "max_tasks:     ${MAX_TASKS}"
    echo "gen_workers:   ${GEN_WORKERS}"
    echo "verify_workers:${VERIFY_WORKERS}"
    echo "pass@k:        ${PASS_K}"
    echo "UNO_POOLS_PATH:${UNO_POOLS_PATH}"
    echo "========================================"
}

cd "${PROJECT_DIR}"
if [[ "${DRY_RUN}" == "1" ]]; then
    printf 'DRY RUN:'
    printf ' %q' "${CMD[@]}"
    printf '\n'
    exit 0
fi

"${CMD[@]}"
"${PYTHON}" - "${OUT_DIR}" <<'PY'
import json
import sys
from pathlib import Path

out_dir = Path(sys.argv[1])
pred_file = out_dir / "predictions.jsonl"
verify_file = out_dir / "verification.jsonl"
trajectory_file = out_dir / "trajectories.json"


def read_jsonl(path: Path) -> list[dict]:
    rows = []
    if not path.exists():
        return rows
    with path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


verifications = {row.get("task_id"): row for row in read_jsonl(verify_file)}
trajectories = []
for pred in read_jsonl(pred_file):
    task_id = pred.get("task_id")
    trajectories.append(
        {
            "task_id": task_id,
            "answer": pred.get("answer", ""),
            "full_trace": pred.get("full_trace", ""),
            "route_count": pred.get("route_count", 0),
            "routed_models": pred.get("routed_models", []),
            "routed_skills": pred.get("routed_skills", []),
            "routed_backends": pred.get("routed_backends", []),
            "cost": pred.get("cost", 0),
            "tokens": pred.get("tokens", 0),
            "prompt_tokens": pred.get("prompt_tokens", 0),
            "completion_tokens": pred.get("completion_tokens", 0),
            "verification": verifications.get(task_id),
        }
    )

with trajectory_file.open("w", encoding="utf-8") as f:
    json.dump(trajectories, f, ensure_ascii=False, indent=2)
    f.write("\n")

print(f"Wrote ToolBench trajectories: {trajectory_file}")
PY
"${PYTHON}" scripts/collect_results.py --root "${EVAL_OUT}" --format md
