#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

if [[ -f "${PROJECT_DIR}/.env" ]]; then
    set -a
    # shellcheck disable=SC1091
    source "${PROJECT_DIR}/.env"
    set +a
fi

UNO_ROUTER_API_BASE="${UNO_ROUTER_API_BASE:-https://notebook-inspire.sii.edu.cn/ws-9dcc0e1f-80a4-4af2-bc2f-0e352e7b17e6/project-b795c114-135a-40db-b3d0-19b60f25237b/user-543feed4-0be2-4972-8987-a324af06c93f/vscode/3a8e9a70-c91e-459d-ad61-e9b54493df6c/1dbfe76a-1f3b-479a-83c4-a1c6377bde6f/proxy/8000/v1}"
PLANNER_MODEL_ID="${PLANNER_MODEL_ID:-Qwen/Qwen2.5-7B-Instruct}"
ROUTER_MODEL_ID="${ROUTER_MODEL_ID:-Qwen/Qwen2.5-7B-Instruct}"
WORKER_MODEL_ID="${WORKER_MODEL_ID:-${OPENROUTER_MODEL:-Qwen/Qwen3-8B}}"
DEEPSEEK_API_BASE="${DEEPSEEK_API_BASE:-https://api.deepseek.com}"
QWEN_API_BASE="${QWEN_API_BASE:-${OPENROUTER_BASE_URL:-https://api.siliconflow.cn/v1}}"
API_BASE="${UNO_ROUTER_API_BASE}"
LOCAL_BASE="${UNO_ROUTER_API_BASE}"
API_KEY="${UNO_ROUTER_API_KEY:-empty}"
QWEN_API_KEY="${QWEN_API_KEY:-${SILICONFLOW_API_KEY:-}}"

if [[ -z "${QWEN_API_KEY}" ]]; then
    echo "QWEN_API_KEY or SILICONFLOW_API_KEY must be set before running this script." >&2
    exit 2
fi

for cert_var in SSL_CERT_FILE REQUESTS_CA_BUNDLE CURL_CA_BUNDLE; do
    cert_path="${!cert_var:-}"
    if [[ -n "${cert_path}" && ! -f "${cert_path}" ]]; then
        : "Unset ${cert_var}: file not found (${cert_path})"
        unset "${cert_var}"
    fi
done

EVAL_OUT="${EVAL_OUT:-${PROJECT_DIR}/data/eval}"
RUN_NAME="${RUN_NAME:-uno_qwen25_7b_qwen3_8b_router_terminalbench}"
GEN_WORKERS="${GEN_WORKERS:-1}"
VERIFY_WORKERS="${VERIFY_WORKERS:-1}"
PASS_K="${PASS_K:-1}"
MAX_TASKS="${MAX_TASKS:-}"
export TERMINALBENCH_TASK_START="${TERMINALBENCH_TASK_START:-1}"
export TERMINALBENCH_TASK_END="${TERMINALBENCH_TASK_END:-}"
# Empty TERMINALBENCH_TASK_IDS means run every Terminal-Bench task discovered by the loader.
export TERMINALBENCH_TASK_IDS="${TERMINALBENCH_TASK_IDS:-cancel-async-tasks}"
export TERMINALBENCH_VERBOSE="${TERMINALBENCH_VERBOSE:-1}"
export TERMINALBENCH_DOCKER_MONITOR="${TERMINALBENCH_DOCKER_MONITOR:-1}"
export TERMINALBENCH_DOCKER_MONITOR_INTERVAL="${TERMINALBENCH_DOCKER_MONITOR_INTERVAL:-20}"
export TERMINALBENCH_DOCKER_IMAGE_PREFIX="${TERMINALBENCH_DOCKER_IMAGE_PREFIX:-alexgshaw}"
export TERMINALBENCH_DOCKER_IMAGE_TAG="${TERMINALBENCH_DOCKER_IMAGE_TAG:-20251031}"
export SUBAGENT_INCLUDE_STEP_LOGS="${SUBAGENT_INCLUDE_STEP_LOGS:-0}"
export SUBAGENT_ENABLE_SKILLS="${SUBAGENT_ENABLE_SKILLS:-0}"
export SUBAGENT_SKILLS_TOP_K="${SUBAGENT_SKILLS_TOP_K:-2}"
export SUBAGENT_SKILLS_MODE="${SUBAGENT_SKILLS_MODE:-task_only}"
export SUBAGENT_SKILLS_MODELS="${SUBAGENT_SKILLS_MODELS:-${WORKER_MODEL_ID}}"
export SUBAGENT_SUMMARY_MODEL_ID="${SUBAGENT_SUMMARY_MODEL_ID:-}"
if [[ -n "${SUBAGENT_SUMMARY_MODEL_ID}" ]]; then
    export SUBAGENT_SUMMARY_API_BASE="${SUBAGENT_SUMMARY_API_BASE:-${DEEPSEEK_API_BASE}}"
    export SUBAGENT_SUMMARY_API_KEY="${SUBAGENT_SUMMARY_API_KEY:-${API_KEY}}"
    export SUBAGENT_SUMMARY_MAX_TOKENS="${SUBAGENT_SUMMARY_MAX_TOKENS:-512}"
fi
export TERMINAL_BENCH_SKILLS_PATH="${TERMINAL_BENCH_SKILLS_PATH:-${PROJECT_DIR}/terminal_bench_skills_init.json}"
ORIGINAL_UNO_POOLS_PATH="${UNO_POOLS_PATH:-${PROJECT_DIR}/configs/pools.deepseek_v32.yaml}"
TIMESTAMP="$(date +%Y%m%d_%H%M)"
OUT_DIR="${EVAL_OUT}/${RUN_NAME}_${TIMESTAMP}"

mkdir -p "${OUT_DIR}"
export UNO_ROUTER_IO_LOG="${UNO_ROUTER_IO_LOG:-${OUT_DIR}/router_prompt_outputs.jsonl}"

FIXED_UNO_POOLS_PATH="${OUT_DIR}/pools.qwen3_8b_fixed_worker.yaml"
cat > "${FIXED_UNO_POOLS_PATH}" <<EOF
policy_models:
  - ${PLANNER_MODEL_ID}
  - ${ROUTER_MODEL_ID}

models:
  - id: ${WORKER_MODEL_ID}
    usd_per_1m_input: 0.072
    usd_per_1m_output: 0.287
    api_base: ${QWEN_API_BASE}
    api_key: ${QWEN_API_KEY}
    description: >
      Alibaba Qwen3 dense 8B worker model. This run-local pool is generated by
      scripts/run_terminalbench_uno_qwen25_7b_qwen3_8b_fixed_routing.sh so Terminal-Bench
      delegation is clamped to ${WORKER_MODEL_ID}.
    allowed_skills:
      - direct_answer
      - reason
      - read_code
      - execute_python
      - execute_shell

skills:
  - id: direct_answer
    description: "Answer the question directly without special tools."
  - id: reason
    description: "Multi-step logical reasoning or chain-of-thought analysis."
  - id: read_code
    description: "Read and understand source code."
  - id: execute_python
    description: "Write and execute Python code to compute a result."
  - id: execute_shell
    description: "Run shell commands for system-level tasks."

fallbacks: {}
pool_ablations: {}
EOF
export UNO_POOLS_PATH="${FIXED_UNO_POOLS_PATH}"

CMD=(
    python -u -m eval_pipeline
    --router planner
    --bench terminalbench
    --api_key "${API_KEY}"
    --api_base "${API_BASE}"
    --local_base "${LOCAL_BASE}"
    --local_model "${PLANNER_MODEL_ID}"
    --router_model "${ROUTER_MODEL_ID}"
    --output_dir "${OUT_DIR}"
    --gen_workers "${GEN_WORKERS}"
    --verify_workers "${VERIFY_WORKERS}"
    --pass-k "${PASS_K}"
    --interactive
)

if [[ -n "${MAX_TASKS}" ]]; then
    CMD+=(--max_tasks "${MAX_TASKS}")
fi

LOG_FILE="${OUT_DIR}/run.log"
RUN_PID=""
MONITOR_PID=""

check_docker() {
    if ! command -v docker >/dev/null 2>&1; then
        {
            echo "Docker preflight failed: docker command not found."
            echo "Install Docker Desktop and ensure docker is available on PATH before running Terminal-Bench."
        } >> "${LOG_FILE}"
        return 1
    fi

    local docker_status
    docker_status="$(docker info 2>&1 >/dev/null)" || {
        {
            echo "Docker preflight failed: Docker daemon is not reachable."
            echo "${docker_status}"
            echo "Start Docker Desktop, wait until the Linux engine is running, then rerun this script."
        } >> "${LOG_FILE}"
        return 1
    }
}

cleanup() {
    local signal="${1:-INT}"
    echo "Received ${signal}; stopping eval process..." >> "${LOG_FILE}"
    if [[ -n "${MONITOR_PID}" ]]; then
        kill "${MONITOR_PID}" 2>/dev/null || true
    fi
    if [[ -n "${RUN_PID}" ]]; then
        kill -INT "${RUN_PID}" 2>/dev/null || true
        sleep 5
        if kill -0 "${RUN_PID}" 2>/dev/null; then
            echo "Eval process still running; sending TERM..." >> "${LOG_FILE}"
            kill -TERM "${RUN_PID}" 2>/dev/null || true
            sleep 2
        fi
        if kill -0 "${RUN_PID}" 2>/dev/null; then
            echo "Eval process still running; sending KILL..." >> "${LOG_FILE}"
            kill -KILL "${RUN_PID}" 2>/dev/null || true
        fi
    fi
    exit 130
}

trap 'cleanup INT' INT
trap 'cleanup TERM' TERM

{
    echo "========================================"
    echo "Terminal-Bench Uno Qwen2.5-7B Router + Qwen3-8B Fixed Routing Eval"
    echo "Project:       ${PROJECT_DIR}"
    echo "Planner model: ${PLANNER_MODEL_ID}"
    echo "Router model:  ${ROUTER_MODEL_ID}"
    echo "Worker model:  ${WORKER_MODEL_ID}"
    echo "API_BASE:      ${API_BASE}"
    echo "LOCAL_BASE:    ${LOCAL_BASE}"
    echo "Output:        ${OUT_DIR}"
    echo "gen_workers:   ${GEN_WORKERS}"
    echo "verify_workers:${VERIFY_WORKERS}"
    echo "pass@k:        ${PASS_K}"
    echo "max_tasks:     ${MAX_TASKS}"
    echo "task_start:    ${TERMINALBENCH_TASK_START}"
    echo "task_end:      ${TERMINALBENCH_TASK_END}"
    echo "task_ids:      ${TERMINALBENCH_TASK_IDS}"
    echo "docker_monitor:${TERMINALBENCH_DOCKER_MONITOR}"
    echo "docker_monitor_interval:${TERMINALBENCH_DOCKER_MONITOR_INTERVAL}"
    echo "docker_image_prefix:${TERMINALBENCH_DOCKER_IMAGE_PREFIX}"
    echo "docker_image_tag:${TERMINALBENCH_DOCKER_IMAGE_TAG}"
    echo "ORIGINAL_UNO_POOLS_PATH:${ORIGINAL_UNO_POOLS_PATH}"
    echo "UNO_POOLS_PATH:${UNO_POOLS_PATH}"
    echo "UNO_ROUTER_IO_LOG:${UNO_ROUTER_IO_LOG}"
    echo "SUBAGENT_INCLUDE_STEP_LOGS:${SUBAGENT_INCLUDE_STEP_LOGS}"
    echo "SUBAGENT_ENABLE_SKILLS:${SUBAGENT_ENABLE_SKILLS}"
    echo "SUBAGENT_SKILLS_TOP_K:${SUBAGENT_SKILLS_TOP_K}"
    echo "SUBAGENT_SKILLS_MODE:${SUBAGENT_SKILLS_MODE}"
    echo "SUBAGENT_SKILLS_MODELS:${SUBAGENT_SKILLS_MODELS}"
    echo "SUBAGENT_SUMMARY_MODEL_ID:${SUBAGENT_SUMMARY_MODEL_ID:-}"
    echo "SUBAGENT_SUMMARY_API_BASE:${SUBAGENT_SUMMARY_API_BASE:-}"
    echo "SUBAGENT_SUMMARY_MAX_TOKENS:${SUBAGENT_SUMMARY_MAX_TOKENS:-}"
    echo "TERMINAL_BENCH_SKILLS_PATH:${TERMINAL_BENCH_SKILLS_PATH}"
    echo "========================================"
} > "${LOG_FILE}"

if ! check_docker; then
    echo "Command failed before eval start. Results: ${OUT_DIR}" >> "${LOG_FILE}"
    exit 2
fi

sanitize_docker_name() {
    python - "$1" <<'PY'
import re
import sys

print(re.sub(r"[^a-z0-9_-]+", "-", sys.argv[1].lower()).strip("-"))
PY
}

monitor_verified_task_docker() {
    local verify_file="${OUT_DIR}/verification.jsonl"
    local monitor_log="${OUT_DIR}/docker_monitor.log"
    local seen_file="${OUT_DIR}/.docker_monitor_seen_tasks"
    local interval="${TERMINALBENCH_DOCKER_MONITOR_INTERVAL}"
    local image_prefix="${TERMINALBENCH_DOCKER_IMAGE_PREFIX}"
    local image_tag="${TERMINALBENCH_DOCKER_IMAGE_TAG}"

    : > "${seen_file}"
    {
        echo "Docker monitor started."
        echo "verification_file: ${verify_file}"
        echo "interval_seconds: ${interval}"
        echo "image_prefix: ${image_prefix}"
        echo "image_tag: ${image_tag}"
    } >> "${monitor_log}"

    while true; do
        if [[ -f "${verify_file}" ]]; then
            while IFS= read -r task_id; do
                [[ -n "${task_id}" ]] || continue
                if grep -Fxq "${task_id}" "${seen_file}" 2>/dev/null; then
                    continue
                fi
                echo "${task_id}" >> "${seen_file}"

                local safe_task_id
                safe_task_id="$(sanitize_docker_name "${task_id}")"
                local prefix="tbench-${safe_task_id}-"
                local image_name="${image_prefix}/${task_id}:${image_tag}"

                echo "[$(date '+%Y-%m-%d %H:%M:%S')] verified task detected: ${task_id}; prefix=${prefix}; image=${image_name}" >> "${monitor_log}"

                while IFS= read -r container_name; do
                    [[ -n "${container_name}" ]] || continue
                    local project_name="${container_name%-main-1}"
                    echo "Stopping stale container: ${container_name}" >> "${monitor_log}"
                    docker rm -f "${container_name}" >> "${monitor_log}" 2>&1 || true
                    if [[ -n "${project_name}" && "${project_name}" != "${container_name}" ]]; then
                        docker network rm "${project_name}_default" >> "${monitor_log}" 2>&1 || true
                    fi
                done < <(
                    docker ps -a --format '{{.Names}}' 2>/dev/null \
                        | grep -E "^${prefix}.*-main-1$" || true
                )

                if docker image inspect "${image_name}" >/dev/null 2>&1; then
                    echo "Removing verified task image: ${image_name}" >> "${monitor_log}"
                    docker rmi "${image_name}" >> "${monitor_log}" 2>&1 || true
                else
                    echo "Task image not present or already removed: ${image_name}" >> "${monitor_log}"
                fi
            done < <(
                python - "${verify_file}" <<'PY'
import json
import sys

path = sys.argv[1]
seen = set()
try:
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                task_id = json.loads(line).get("task_id")
            except json.JSONDecodeError:
                continue
            if task_id and task_id not in seen:
                seen.add(task_id)
                print(task_id)
except FileNotFoundError:
    pass
PY
            )
        fi
        sleep "${interval}"
    done
}

cd "${PROJECT_DIR}"
if [[ "${TERMINALBENCH_DOCKER_MONITOR}" == "1" ]]; then
    monitor_verified_task_docker &
    MONITOR_PID=$!
    echo "Docker monitor enabled with pid ${MONITOR_PID}." >> "${LOG_FILE}"
fi
"${CMD[@]}" >> "${LOG_FILE}" 2>&1 &
RUN_PID=$!
wait "${RUN_PID}"
STATUS=$?
trap - INT TERM

if [[ -n "${MONITOR_PID}" ]]; then
    kill "${MONITOR_PID}" 2>/dev/null || true
    wait "${MONITOR_PID}" 2>/dev/null || true
fi

if [[ "${STATUS}" -ne 0 ]]; then
    echo "Command failed with status ${STATUS}. Results: ${OUT_DIR}" >> "${LOG_FILE}"
    exit "${STATUS}"
fi

{
    echo "Done. Results: ${OUT_DIR}"
} >> "${LOG_FILE}"
