#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

if [[ -f "${PROJECT_DIR}/.env" ]]; then
    set -a
    # shellcheck disable=SC1091
    source "${PROJECT_DIR}/.env"
    set +a
fi

PLANNER_MODEL_ID="${PLANNER_MODEL_ID:-${MODEL_ID:-${DEEPSEEK_MODEL_ID:-deepseek-v4-flash}}}"
ROUTER_MODEL_ID="${ROUTER_MODEL_ID:-deepseek-v4-flash}"
WORKER_MODEL_ID="${WORKER_MODEL_ID:-deepseek-v4-pro}"
DEEPSEEK_API_BASE="${DEEPSEEK_API_BASE:-https://api.deepseek.com}"
API_BASE="${DEEPSEEK_API_BASE}"
LOCAL_BASE="${DEEPSEEK_API_BASE}"
API_KEY="${DEEPSEEK_API_KEY:-${API_KEY:-}}"

if [[ -z "${API_KEY}" ]]; then
    echo "DEEPSEEK_API_KEY or API_KEY must be set before running this script." >&2
    exit 2
fi

for cert_var in SSL_CERT_FILE REQUESTS_CA_BUNDLE CURL_CA_BUNDLE; do
    cert_path="${!cert_var:-}"
    if [[ -n "${cert_path}" && ! -f "${cert_path}" ]]; then
        : "Unset ${cert_var}: file not found (${cert_path})"
        unset "${cert_var}"
    fi
done

EVAL_OUT="${EVAL_OUT:-${PROJECT_DIR}/data/eval}"
RUN_NAME="${RUN_NAME:-deepseek_v4_pro_planner_terminalbench}"
GEN_WORKERS="${GEN_WORKERS:-4}"
VERIFY_WORKERS="${VERIFY_WORKERS:-2}"
PASS_K="${PASS_K:-2}"
MAX_TASKS="${MAX_TASKS:-}"
export TERMINALBENCH_TASK_START="${TERMINALBENCH_TASK_START:-1}"
export TERMINALBENCH_TASK_END="${TERMINALBENCH_TASK_END:-}"
# Empty TERMINALBENCH_TASK_IDS means run every Terminal-Bench task discovered by the loader.
export TERMINALBENCH_TASK_IDS="${TERMINALBENCH_TASK_IDS:-}"
export TERMINALBENCH_VERBOSE="${TERMINALBENCH_VERBOSE:-1}"
export TERMINALBENCH_DOCKER_MONITOR="${TERMINALBENCH_DOCKER_MONITOR:-1}"
export TERMINALBENCH_DOCKER_MONITOR_INTERVAL="${TERMINALBENCH_DOCKER_MONITOR_INTERVAL:-20}"
export TERMINALBENCH_DOCKER_IMAGE_PREFIX="${TERMINALBENCH_DOCKER_IMAGE_PREFIX:-alexgshaw}"
export TERMINALBENCH_DOCKER_IMAGE_TAG="${TERMINALBENCH_DOCKER_IMAGE_TAG:-20251031}"
export SUBAGENT_INCLUDE_STEP_LOGS="${SUBAGENT_INCLUDE_STEP_LOGS:-0}"
export SUBAGENT_ENABLE_SKILLS="${SUBAGENT_ENABLE_SKILLS:-0}"
export SUBAGENT_SKILLS_TOP_K="${SUBAGENT_SKILLS_TOP_K:-2}"
export SUBAGENT_SKILLS_MODE="${SUBAGENT_SKILLS_MODE:-task_only}"
export SUBAGENT_SKILLS_MODELS="${SUBAGENT_SKILLS_MODELS:-${WORKER_MODEL_ID}}"
export SUBAGENT_SUMMARY_MODEL_ID="${SUBAGENT_SUMMARY_MODEL_ID:-}"
if [[ -n "${SUBAGENT_SUMMARY_MODEL_ID}" ]]; then
    export SUBAGENT_SUMMARY_API_BASE="${SUBAGENT_SUMMARY_API_BASE:-${DEEPSEEK_API_BASE}}"
    export SUBAGENT_SUMMARY_API_KEY="${SUBAGENT_SUMMARY_API_KEY:-${API_KEY}}"
    export SUBAGENT_SUMMARY_MAX_TOKENS="${SUBAGENT_SUMMARY_MAX_TOKENS:-512}"
fi
export TERMINAL_BENCH_SKILLS_PATH="${TERMINAL_BENCH_SKILLS_PATH:-${PROJECT_DIR}/terminal_bench_skills_init.json}"
ORIGINAL_UNO_POOLS_PATH="${UNO_POOLS_PATH:-${PROJECT_DIR}/configs/pools.deepseek_v32.yaml}"
TIMESTAMP="$(date +%Y%m%d_%H%M)"
OUT_DIR="${EVAL_OUT}/${RUN_NAME}_${TIMESTAMP}"

mkdir -p "${OUT_DIR}"

FIXED_UNO_POOLS_PATH="${OUT_DIR}/pools.deepseek_v4_pro_worker.yaml"
cat > "${FIXED_UNO_POOLS_PATH}" <<EOF
policy_models:
  - ${PLANNER_MODEL_ID}
  - ${ROUTER_MODEL_ID}

models:
  - id: ${WORKER_MODEL_ID}
    usd_per_1m_input: 3
    usd_per_1m_output: 6
    api_base: ${DEEPSEEK_API_BASE}
    api_key: ${API_KEY}
    description: >
      DeepSeek v4 pro worker model. This run-local pool is generated by
      scripts/run_terminalbench_deepseek_v4_pro.sh so Terminal-Bench
      delegation is clamped to ${WORKER_MODEL_ID}.
    allowed_skills:
      - direct_answer
      - reason
      - read_code
      - execute_python
      - execute_shell

skills:
  - id: direct_answer
    description: "Answer the question directly without special tools."
  - id: reason
    description: "Multi-step logical reasoning or chain-of-thought analysis."
  - id: read_code
    description: "Read and understand source code."
  - id: execute_python
    description: "Write and execute Python code to compute a result."
  - id: execute_shell
    description: "Run shell commands for system-level tasks."

fallbacks: {}
pool_ablations: {}
EOF
export UNO_POOLS_PATH="${FIXED_UNO_POOLS_PATH}"

CMD=(
    python -u -m eval_pipeline
    --router planner
    --bench terminalbench
    --api_key "${API_KEY}"
    --api_base "${API_BASE}"
    --local_base "${LOCAL_BASE}"
    --local_model "${PLANNER_MODEL_ID}"
    --router_model "${ROUTER_MODEL_ID}"
    --output_dir "${OUT_DIR}"
    --gen_workers "${GEN_WORKERS}"
    --verify_workers "${VERIFY_WORKERS}"
    --pass-k "${PASS_K}"
    --interactive
)

if [[ -n "${MAX_TASKS}" ]]; then
    CMD+=(--max_tasks "${MAX_TASKS}")
fi

LOG_FILE="${OUT_DIR}/run.log"
RUN_PID=""

# shellcheck source=scripts/terminalbench_docker_cleanup_monitor.sh
source "${PROJECT_DIR}/scripts/terminalbench_docker_cleanup_monitor.sh"

check_docker() {
    if ! command -v docker >/dev/null 2>&1; then
        {
            echo "Docker preflight failed: docker command not found."
            echo "Install Docker Desktop and ensure docker is available on PATH before running Terminal-Bench."
        } >> "${LOG_FILE}"
        return 1
    fi

    local docker_status
    docker_status="$(docker info 2>&1 >/dev/null)" || {
        {
            echo "Docker preflight failed: Docker daemon is not reachable."
            echo "${docker_status}"
            echo "Start Docker Desktop, wait until the Linux engine is running, then rerun this script."
        } >> "${LOG_FILE}"
        return 1
    }
}

cleanup() {
    local signal="${1:-INT}"
    echo "Received ${signal}; stopping eval process..." >> "${LOG_FILE}"
    terminalbench_stop_docker_cleanup_monitor
    if [[ -n "${RUN_PID}" ]]; then
        kill -INT "${RUN_PID}" 2>/dev/null || true
        sleep 5
        if kill -0 "${RUN_PID}" 2>/dev/null; then
            echo "Eval process still running; sending TERM..." >> "${LOG_FILE}"
            kill -TERM "${RUN_PID}" 2>/dev/null || true
            sleep 2
        fi
        if kill -0 "${RUN_PID}" 2>/dev/null; then
            echo "Eval process still running; sending KILL..." >> "${LOG_FILE}"
            kill -KILL "${RUN_PID}" 2>/dev/null || true
        fi
    fi
    exit 130
}

trap 'cleanup INT' INT
trap 'cleanup TERM' TERM

{
    echo "========================================"
    echo "Terminal-Bench DeepSeek v4 Pro Planner Eval"
    echo "Project:       ${PROJECT_DIR}"
    echo "Planner model: ${PLANNER_MODEL_ID}"
    echo "Router model:  ${ROUTER_MODEL_ID}"
    echo "Worker model:  ${WORKER_MODEL_ID}"
    echo "API_BASE:      ${API_BASE}"
    echo "LOCAL_BASE:    ${LOCAL_BASE}"
    echo "Output:        ${OUT_DIR}"
    echo "gen_workers:   ${GEN_WORKERS}"
    echo "verify_workers:${VERIFY_WORKERS}"
    echo "pass@k:        ${PASS_K}"
    echo "max_tasks:     ${MAX_TASKS}"
    echo "task_start:    ${TERMINALBENCH_TASK_START}"
    echo "task_end:      ${TERMINALBENCH_TASK_END}"
    echo "task_ids:      ${TERMINALBENCH_TASK_IDS}"
    echo "docker_monitor:${TERMINALBENCH_DOCKER_MONITOR}"
    echo "docker_monitor_interval:${TERMINALBENCH_DOCKER_MONITOR_INTERVAL}"
    echo "docker_image_prefix:${TERMINALBENCH_DOCKER_IMAGE_PREFIX}"
    echo "docker_image_tag:${TERMINALBENCH_DOCKER_IMAGE_TAG}"
    echo "ORIGINAL_UNO_POOLS_PATH:${ORIGINAL_UNO_POOLS_PATH}"
    echo "UNO_POOLS_PATH:${UNO_POOLS_PATH}"
    echo "SUBAGENT_INCLUDE_STEP_LOGS:${SUBAGENT_INCLUDE_STEP_LOGS}"
    echo "SUBAGENT_ENABLE_SKILLS:${SUBAGENT_ENABLE_SKILLS}"
    echo "SUBAGENT_SKILLS_TOP_K:${SUBAGENT_SKILLS_TOP_K}"
    echo "SUBAGENT_SKILLS_MODE:${SUBAGENT_SKILLS_MODE}"
    echo "SUBAGENT_SKILLS_MODELS:${SUBAGENT_SKILLS_MODELS}"
    echo "SUBAGENT_SUMMARY_MODEL_ID:${SUBAGENT_SUMMARY_MODEL_ID:-}"
    echo "SUBAGENT_SUMMARY_API_BASE:${SUBAGENT_SUMMARY_API_BASE:-}"
    echo "SUBAGENT_SUMMARY_MAX_TOKENS:${SUBAGENT_SUMMARY_MAX_TOKENS:-}"
    echo "TERMINAL_BENCH_SKILLS_PATH:${TERMINAL_BENCH_SKILLS_PATH}"
    echo "========================================"
} > "${LOG_FILE}"

if ! check_docker; then
    echo "Command failed before eval start. Results: ${OUT_DIR}" >> "${LOG_FILE}"
    exit 2
fi

cd "${PROJECT_DIR}"
terminalbench_start_docker_cleanup_monitor "${OUT_DIR}" "${LOG_FILE}"
"${CMD[@]}" >> "${LOG_FILE}" 2>&1 &
RUN_PID=$!
wait "${RUN_PID}"
STATUS=$?
trap - INT TERM
terminalbench_stop_docker_cleanup_monitor

if [[ "${STATUS}" -ne 0 ]]; then
    echo "Command failed with status ${STATUS}. Results: ${OUT_DIR}" >> "${LOG_FILE}"
    exit "${STATUS}"
fi

{
    echo "Done. Results: ${OUT_DIR}"
} >> "${LOG_FILE}"

