#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

if [[ -f "${PROJECT_DIR}/.env" ]]; then
    set -a
    # shellcheck disable=SC1091
    source "${PROJECT_DIR}/.env"
    set +a
fi

MODEL_ID="${MODEL_ID:-${DEEPSEEK_MODEL_ID:-deepseek-v4-flash}}"
ROUTER_MODEL_ID="${ROUTER_MODEL_ID:-Qwen/Qwen3-8B}"
FIXED_WORKER_MODEL_ID="${FIXED_WORKER_MODEL_ID:-Qwen/Qwen3-8B}"
DEEPSEEK_API_BASE="${DEEPSEEK_API_BASE:-https://api.deepseek.com}"
QWEN_API_BASE="${QWEN_API_BASE:-https://api.siliconflow.com/v1}"
API_BASE="${DEEPSEEK_API_BASE}"
LOCAL_BASE="${DEEPSEEK_API_BASE}"
API_KEY="${DEEPSEEK_API_KEY:-${API_KEY:-}}"
QWEN_API_KEY="${QWEN_API_KEY:-${SILICONFLOW_API_KEY:-}}"

if [[ -z "${API_KEY}" ]]; then
    echo "DEEPSEEK_API_KEY or API_KEY must be set before running this script." >&2
    exit 2
fi
if [[ -z "${QWEN_API_KEY}" ]]; then
    echo "QWEN_API_KEY or SILICONFLOW_API_KEY must be set before running this script." >&2
    exit 2
fi

for cert_var in SSL_CERT_FILE REQUESTS_CA_BUNDLE CURL_CA_BUNDLE; do
    cert_path="${!cert_var:-}"
    if [[ -n "${cert_path}" && ! -f "${cert_path}" ]]; then
        : "Unset ${cert_var}: file not found (${cert_path})"
        unset "${cert_var}"
    fi
done

EVAL_OUT="${EVAL_OUT:-${PROJECT_DIR}/data/eval}"
RUN_NAME="${RUN_NAME:-deepseek_v4_pro_qwen3_8b_router_terminalbench_gen_skills}"
GEN_WORKERS="${GEN_WORKERS:-4}"
VERIFY_WORKERS="${VERIFY_WORKERS:-2}"
PASS_K="${PASS_K:-2}"
MAX_TASKS="${MAX_TASKS:-}"
export TERMINALBENCH_TASK_START="${TERMINALBENCH_TASK_START:-1}"
export TERMINALBENCH_TASK_END="${TERMINALBENCH_TASK_END:-}"
export TERMINALBENCH_TASK_IDS="${TERMINALBENCH_TASK_IDS:-bn-fit-modify,cancel-async-tasks,code-from-image,configure-git-webserver,count-dataset-tokens,extract-elf,build-pov-ray,circuit-fibsqrt,compile-compcert}"
export TERMINALBENCH_VERBOSE="${TERMINALBENCH_VERBOSE:-1}"
export SUBAGENT_INCLUDE_STEP_LOGS="${SUBAGENT_INCLUDE_STEP_LOGS:-0}"
export SUBAGENT_ENABLE_SKILLS="${SUBAGENT_ENABLE_SKILLS:-0}"
export SUBAGENT_SKILLS_TOP_K="${SUBAGENT_SKILLS_TOP_K:-2}"
export SUBAGENT_SKILLS_MODE="${SUBAGENT_SKILLS_MODE:-task_only}"
export SUBAGENT_SKILLS_MODELS="${SUBAGENT_SKILLS_MODELS:-${ROUTER_MODEL_ID}}"
export SUBAGENT_SUMMARY_MODEL_ID="${SUBAGENT_SUMMARY_MODEL_ID:-deepseek-v4-flash}"
export SUBAGENT_SUMMARY_API_BASE="${SUBAGENT_SUMMARY_API_BASE:-${DEEPSEEK_API_BASE}}"
export SUBAGENT_SUMMARY_API_KEY="${SUBAGENT_SUMMARY_API_KEY:-${API_KEY}}"
export SUBAGENT_SUMMARY_MAX_TOKENS="${SUBAGENT_SUMMARY_MAX_TOKENS:-512}"
export TERMINAL_BENCH_SKILLS_PATH="${TERMINAL_BENCH_SKILLS_PATH:-${PROJECT_DIR}/terminal_bench_skills_gen.json}"
ORIGINAL_UNO_POOLS_PATH="${UNO_POOLS_PATH:-${PROJECT_DIR}/configs/pools.deepseek_v32.yaml}"
RUN_ID="${RUN_ID:-}"
OUT_DIR="${OUT_DIR:-${EVAL_OUT}/${RUN_NAME}${RUN_ID:+_${RUN_ID}}}"
TBENCH_PRUNE_STALE_NETWORKS="${TBENCH_PRUNE_STALE_NETWORKS:-1}"

mkdir -p "${OUT_DIR}"

export TERMINALBENCH_PROMPT_DUMP_DIR="${TERMINALBENCH_PROMPT_DUMP_DIR:-${OUT_DIR}/prompt_dumps}"
export TERMINALBENCH_PROMPT_DUMP_TASK_LIMIT="${TERMINALBENCH_PROMPT_DUMP_TASK_LIMIT:-1}"

if [[ "${SUBAGENT_ENABLE_SKILLS}" != "0" && ! -f "${TERMINAL_BENCH_SKILLS_PATH}" ]]; then
    echo "Missing skills file: ${TERMINAL_BENCH_SKILLS_PATH}" >&2
    echo "Generate it first with scripts/run_distill_terminalbench_skills.sh or set TERMINAL_BENCH_SKILLS_PATH." >&2
    exit 1
fi

FIXED_UNO_POOLS_PATH="${OUT_DIR}/pools.qwen3_8b_fixed_worker.yaml"
cat > "${FIXED_UNO_POOLS_PATH}" <<EOF
policy_models:
  - ${MODEL_ID}
  - ${ROUTER_MODEL_ID}

models:
  - id: ${FIXED_WORKER_MODEL_ID}
    usd_per_1m_input: 0.072
    usd_per_1m_output: 0.287
    api_base: ${QWEN_API_BASE}
    api_key: ${QWEN_API_KEY}
    description: >
      Alibaba Qwen3 dense 8B model served through SiliconFlow. This run-local
      pool is generated by scripts/run_terminalbench_qwen3_8b_fixed_routing_gen_skills.sh
      so Terminal-Bench delegation is clamped to Qwen/Qwen3-8B without changing
      the repository's normal pool configuration.
    allowed_skills:
      - direct_answer
      - reason
      - read_code
      - execute_python
      - execute_shell

skills:
  - id: direct_answer
    description: "Answer the question directly without special tools."
  - id: reason
    description: "Multi-step logical reasoning or chain-of-thought analysis."
  - id: read_code
    description: "Read and understand source code."
  - id: execute_python
    description: "Write and execute Python code to compute a result."
  - id: execute_shell
    description: "Run shell commands for system-level tasks."

fallbacks: {}
pool_ablations: {}
EOF
export UNO_POOLS_PATH="${FIXED_UNO_POOLS_PATH}"

CMD=(
    python -u -m eval_pipeline
    --router planner
    --bench terminalbench
    --api_key "${API_KEY}"
    --api_base "${API_BASE}"
    --local_base "${LOCAL_BASE}"
    --local_model "${MODEL_ID}"
    --router_model "${ROUTER_MODEL_ID}"
    --output_dir "${OUT_DIR}"
    --gen_workers "${GEN_WORKERS}"
    --verify_workers "${VERIFY_WORKERS}"
    --pass-k "${PASS_K}"
    --interactive
)

if [[ -n "${MAX_TASKS}" ]]; then
    CMD+=(--max_tasks "${MAX_TASKS}")
fi

RUN_LOG_TS="$(date +%Y%m%d_%H%M%S)"
LOG_FILE="${OUT_DIR}/log_${RUN_LOG_TS}.log"

if [[ "${TBENCH_PRUNE_STALE_NETWORKS}" != "0" ]]; then
    {
        echo "Pruning stale Terminal-Bench docker networks before run..."
        if command -v docker >/dev/null 2>&1; then
            docker network ls --format '{{.ID}} {{.Name}}' \
                | awk '$2 ~ /^tbench-/ {print $1}' \
                | while read -r network_id; do
                    [[ -n "${network_id}" ]] && docker network rm "${network_id}" || true
                done
        else
            echo "docker command not found; skip network pruning"
        fi
    } >> "${LOG_FILE}" 2>&1 || true
fi

{
    echo "========================================"
    echo "Terminal-Bench DeepSeek Planner + Qwen3-8B Router Eval + Generated Skills"
    echo "Project:       ${PROJECT_DIR}"
    echo "Model:         ${MODEL_ID}"
    echo "Router model:  ${ROUTER_MODEL_ID}"
    echo "Fixed worker:  ${FIXED_WORKER_MODEL_ID}"
    echo "API_BASE:      ${API_BASE}"
    echo "LOCAL_BASE:    ${LOCAL_BASE}"
    echo "Output:        ${OUT_DIR}"
    echo "gen_workers:   ${GEN_WORKERS}"
    echo "verify_workers:${VERIFY_WORKERS}"
    echo "pass@k:        ${PASS_K}"
    echo "max_tasks:     ${MAX_TASKS}"
    echo "task_start:    ${TERMINALBENCH_TASK_START}"
    echo "task_end:      ${TERMINALBENCH_TASK_END}"
    echo "task_ids:      ${TERMINALBENCH_TASK_IDS}"
    echo "resume:        enabled (reuse OUT_DIR to skip completed tasks)"
    echo "ORIGINAL_UNO_POOLS_PATH:${ORIGINAL_UNO_POOLS_PATH}"
    echo "UNO_POOLS_PATH:${UNO_POOLS_PATH}"
    echo "SUBAGENT_INCLUDE_STEP_LOGS:${SUBAGENT_INCLUDE_STEP_LOGS}"
    echo "SUBAGENT_ENABLE_SKILLS:${SUBAGENT_ENABLE_SKILLS}"
    echo "SUBAGENT_SKILLS_TOP_K:${SUBAGENT_SKILLS_TOP_K}"
    echo "SUBAGENT_SKILLS_MODE:${SUBAGENT_SKILLS_MODE}"
    echo "SUBAGENT_SKILLS_MODELS:${SUBAGENT_SKILLS_MODELS}"
    echo "SUBAGENT_SUMMARY_MODEL_ID:${SUBAGENT_SUMMARY_MODEL_ID}"
    echo "SUBAGENT_SUMMARY_API_BASE:${SUBAGENT_SUMMARY_API_BASE}"
    echo "SUBAGENT_SUMMARY_MAX_TOKENS:${SUBAGENT_SUMMARY_MAX_TOKENS}"
    echo "TERMINAL_BENCH_SKILLS_PATH:${TERMINAL_BENCH_SKILLS_PATH}"
    echo "TERMINALBENCH_PROMPT_DUMP_DIR:${TERMINALBENCH_PROMPT_DUMP_DIR}"
    echo "TERMINALBENCH_PROMPT_DUMP_TASK_LIMIT:${TERMINALBENCH_PROMPT_DUMP_TASK_LIMIT}"
    echo "TBENCH_PRUNE_STALE_NETWORKS:${TBENCH_PRUNE_STALE_NETWORKS}"
    echo "========================================"
} >> "${LOG_FILE}"

python - "${OUT_DIR}" "${PROJECT_DIR}" "${TERMINALBENCH_TASK_START}" "${TERMINALBENCH_TASK_END}" "${TERMINALBENCH_TASK_IDS}" >> "${LOG_FILE}" 2>&1 <<'PY'
import json
import shutil
import sys
import re
from pathlib import Path

out_dir = Path(sys.argv[1])
project_dir = Path(sys.argv[2])
task_start = int(sys.argv[3] or "1")
task_end = int(sys.argv[4]) if sys.argv[4] else None
task_ids_raw = sys.argv[5] if len(sys.argv) > 5 else ""
allowed_task_ids = {
    item.strip()
    for item in re.split(r"[,\s]+", task_ids_raw)
    if item.strip()
}
pred_file = out_dir / "predictions.jsonl"
verify_file = out_dir / "verification.jsonl"
logs_dir = out_dir / "logs"
tasks_root = project_dir / "data" / "terminal-bench" / "tasks"


def load_latest(path: Path) -> dict[str, dict]:
    latest = {}
    if not path.exists():
        return latest
    with path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            task_id = row.get("task_id")
            if task_id:
                latest[task_id] = row
    return latest


def write_jsonl(path: Path, rows: list[dict]) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")
    tmp.replace(path)


predictions = load_latest(pred_file)
verification = load_latest(verify_file)
verified_ids = set(verification)

task_names = sorted(
    path.name
    for path in tasks_root.iterdir()
    if path.is_dir()
) if tasks_root.exists() else []
selected_ids = {
    name
    for idx, name in enumerate(task_names, start=1)
    if idx >= task_start
    and (task_end is None or idx <= task_end)
    and (not allowed_task_ids or name in allowed_task_ids)
}

write_jsonl(verify_file, [verification[task_id] for task_id in verification])
write_jsonl(pred_file, [
    predictions[task_id]
    for task_id in predictions
    if task_id in verified_ids or task_id not in selected_ids
])

removed_log_dirs = 0
if logs_dir.exists():
    for attempt_dir in logs_dir.glob("attempt_*"):
        if not attempt_dir.is_dir():
            continue
        for task_dir in attempt_dir.iterdir():
            if (
                task_dir.is_dir()
                and task_dir.name in selected_ids
                and task_dir.name not in verified_ids
            ):
                shutil.rmtree(task_dir)
                removed_log_dirs += 1

removed_prediction_ids = sorted((set(predictions) & selected_ids) - verified_ids)
if removed_prediction_ids or removed_log_dirs:
    print(
        "Prepared pass@k-preserving resume: "
        f"removed_unverified_predictions={removed_prediction_ids}; "
        f"removed_unverified_log_dirs={removed_log_dirs}"
    )
else:
    print("No unverified task outputs needed cleanup.")
PY

cd "${PROJECT_DIR}"
"${CMD[@]}" >> "${LOG_FILE}" 2>&1

{
    echo "Done. Results: ${OUT_DIR}"
} >> "${LOG_FILE}"
